repos:
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.20.0
    hooks:
      - id: stylua
        args: ["--check"]

  - repo: https://github.com/JohnnyMorganz/Selene
    rev: v0.24.0
    hooks:
      - id: selene
